name: IA Code Review (Central)

on:
  workflow_call:
    secrets:
      GEMINI_KEY:
        required: true

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      
    steps:
      - name: Checkout do código do PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout do script de IA
        uses: actions/checkout@v4
        with:
          repository: 'DeivisonJohnny/Code-review-IA' 
          path: 'ia-review' # A pasta temporária agora se chama ia-review

      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependências da IA
        run: npm install @google/genai tsx

      - name: Extrair o Diff do PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr diff ${{ github.event.pull_request.number }} > diff.txt

      - name: Executar o Script de IA
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_NAME: ${{ github.repository }}
        run: npx tsx ia-review/.github/scripts/review.ts